### ISSUE TITLE
The each() function is deprecated

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [tintnaingwinn/email-checker#1]
`            $mxs[$hosts[$n]] = $mxRecords[$n];
        }
 
        asort($mxs);
 
        array_push($mxs, $this->domain);
 
        $timeout = $this->max_conn_time/(count($hosts)>0 ? count($hosts) : 1);
 
        // connect to SMTP
        while(list($host) = each($mxs))
        {
            if ($this->socket = @fsockopen($host, $this->port, $errno, $errstr, (float) $timeout))
            {
                stream_set_timeout($this->socket, $this->max_read_time);
                break;
            }
        }
 
        if ($this->socket)
        {
            $reply = fread($this->socket, 2082);
 
            preg_match('/^([0-9]{3})/ims', $reply, $matches);
            $code = isset($matches[1]) ? $matches[1] : '';`

**Comment by tintnaingwin** [comment]
Thanks for your report . I will update soon .

**Comment by tintnaingwin** [comment]
fixed on v1.0
