### ISSUE TITLE
The validation does not interrupt the registration when the email is non-existent (fake)

### ISSUE THREAD

**Issue by arturbruno** [tintnaingwinn/email-checker#4]
Hello. I'm having a problem using the package. Although adding "email_checker" in the rules for validation of the email field, the registration is still accepted when the email is non-existent and the data is registered in the database. The other validation rules: email, require, max, and unique work normally. The installation of the package was done correctly by adding the Facade and the Provider. I would be grateful for a response to the problem. Follow the code of the rule in the Registration Request:

```
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'email' => 'bail|required|email|max:255|unique:users|email_checker',
            'identificador' => 'required|cpf_cnpj|unique:users,identificador',
            'password' => [
                'confirmed',
                'required',
                'regex:/[a-zA-Z]/',
                'regex:/[0-9]/',
                'min:8'
            ],
            'tipo' => 'required|size:1|alpha',
        ];
    }
```

**Comment by tintnaingwin** [comment]
Hi, sorry for not reacting, I had checked on my side. It's all ok. I'm not clear. Has already been taken the email on the database?
